{
 "title": "Container Metrics",
 "tags": [ "demo" ],
 "refresh": "10s",
 "panels": [
  {
   "title": "Running Containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(container_last_seen{name!=\"\"})"
    }
   ]
  },
  {
   "title": "CPU per Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name!=\"\"}[2m])*100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory per Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name!=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}